// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analyzer.proto

package pulumirpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _struct "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EnforcementLevel indicates the severity of a policy violation.
type AnalyzeDiagnostic_LogSeverity int32

const (
	AnalyzeDiagnostic_INFORMATIONAL  AnalyzeDiagnostic_LogSeverity = 0
	AnalyzeDiagnostic_SOFT_MANDATORY AnalyzeDiagnostic_LogSeverity = 1
	AnalyzeDiagnostic_HARD_MANDATORY AnalyzeDiagnostic_LogSeverity = 2
)

var AnalyzeDiagnostic_LogSeverity_name = map[int32]string{
	0: "INFORMATIONAL",
	1: "SOFT_MANDATORY",
	2: "HARD_MANDATORY",
}
var AnalyzeDiagnostic_LogSeverity_value = map[string]int32{
	"INFORMATIONAL":  0,
	"SOFT_MANDATORY": 1,
	"HARD_MANDATORY": 2,
}

func (x AnalyzeDiagnostic_LogSeverity) String() string {
	return proto.EnumName(AnalyzeDiagnostic_LogSeverity_name, int32(x))
}
func (AnalyzeDiagnostic_LogSeverity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_88854e5a6788f689, []int{2, 0}
}

type AnalyzeRequest struct {
	Type                 string          `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Properties           *_struct.Struct `protobuf:"bytes,2,opt,name=properties" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AnalyzeRequest) Reset()         { *m = AnalyzeRequest{} }
func (m *AnalyzeRequest) String() string { return proto.CompactTextString(m) }
func (*AnalyzeRequest) ProtoMessage()    {}
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_88854e5a6788f689, []int{0}
}
func (m *AnalyzeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeRequest.Unmarshal(m, b)
}
func (m *AnalyzeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeRequest.Marshal(b, m, deterministic)
}
func (dst *AnalyzeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeRequest.Merge(dst, src)
}
func (m *AnalyzeRequest) XXX_Size() int {
	return xxx_messageInfo_AnalyzeRequest.Size(m)
}
func (m *AnalyzeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeRequest proto.InternalMessageInfo

func (m *AnalyzeRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AnalyzeRequest) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

type AnalyzeResponse struct {
	Diagnostics          []*AnalyzeDiagnostic `protobuf:"bytes,1,rep,name=diagnostics" json:"diagnostics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AnalyzeResponse) Reset()         { *m = AnalyzeResponse{} }
func (m *AnalyzeResponse) String() string { return proto.CompactTextString(m) }
func (*AnalyzeResponse) ProtoMessage()    {}
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_88854e5a6788f689, []int{1}
}
func (m *AnalyzeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeResponse.Unmarshal(m, b)
}
func (m *AnalyzeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeResponse.Marshal(b, m, deterministic)
}
func (dst *AnalyzeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeResponse.Merge(dst, src)
}
func (m *AnalyzeResponse) XXX_Size() int {
	return xxx_messageInfo_AnalyzeResponse.Size(m)
}
func (m *AnalyzeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeResponse proto.InternalMessageInfo

func (m *AnalyzeResponse) GetDiagnostics() []*AnalyzeDiagnostic {
	if m != nil {
		return m.Diagnostics
	}
	return nil
}

type AnalyzeDiagnostic struct {
	Name                 string                        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description          string                        `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Message              string                        `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Tags                 []string                      `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	EnforcementLevel     AnalyzeDiagnostic_LogSeverity `protobuf:"varint,5,opt,name=enforcementLevel,enum=pulumirpc.AnalyzeDiagnostic_LogSeverity" json:"enforcementLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *AnalyzeDiagnostic) Reset()         { *m = AnalyzeDiagnostic{} }
func (m *AnalyzeDiagnostic) String() string { return proto.CompactTextString(m) }
func (*AnalyzeDiagnostic) ProtoMessage()    {}
func (*AnalyzeDiagnostic) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_88854e5a6788f689, []int{2}
}
func (m *AnalyzeDiagnostic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeDiagnostic.Unmarshal(m, b)
}
func (m *AnalyzeDiagnostic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeDiagnostic.Marshal(b, m, deterministic)
}
func (dst *AnalyzeDiagnostic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeDiagnostic.Merge(dst, src)
}
func (m *AnalyzeDiagnostic) XXX_Size() int {
	return xxx_messageInfo_AnalyzeDiagnostic.Size(m)
}
func (m *AnalyzeDiagnostic) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeDiagnostic.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeDiagnostic proto.InternalMessageInfo

func (m *AnalyzeDiagnostic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnalyzeDiagnostic) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AnalyzeDiagnostic) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AnalyzeDiagnostic) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AnalyzeDiagnostic) GetEnforcementLevel() AnalyzeDiagnostic_LogSeverity {
	if m != nil {
		return m.EnforcementLevel
	}
	return AnalyzeDiagnostic_INFORMATIONAL
}

func init() {
	proto.RegisterType((*AnalyzeRequest)(nil), "pulumirpc.AnalyzeRequest")
	proto.RegisterType((*AnalyzeResponse)(nil), "pulumirpc.AnalyzeResponse")
	proto.RegisterType((*AnalyzeDiagnostic)(nil), "pulumirpc.AnalyzeDiagnostic")
	proto.RegisterEnum("pulumirpc.AnalyzeDiagnostic_LogSeverity", AnalyzeDiagnostic_LogSeverity_name, AnalyzeDiagnostic_LogSeverity_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Analyzer service

type AnalyzerClient interface {
	// Analyze analyzes a single resource object, and returns any errors that it finds.
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	// GetPluginInfo returns generic information about this plugin, like its version.
	GetPluginInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PluginInfo, error)
}

type analyzerClient struct {
	cc *grpc.ClientConn
}

func NewAnalyzerClient(cc *grpc.ClientConn) AnalyzerClient {
	return &analyzerClient{cc}
}

func (c *analyzerClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	out := new(AnalyzeResponse)
	err := grpc.Invoke(ctx, "/pulumirpc.Analyzer/Analyze", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerClient) GetPluginInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	out := new(PluginInfo)
	err := grpc.Invoke(ctx, "/pulumirpc.Analyzer/GetPluginInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Analyzer service

type AnalyzerServer interface {
	// Analyze analyzes a single resource object, and returns any errors that it finds.
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	// GetPluginInfo returns generic information about this plugin, like its version.
	GetPluginInfo(context.Context, *empty.Empty) (*PluginInfo, error)
}

func RegisterAnalyzerServer(s *grpc.Server, srv AnalyzerServer) {
	s.RegisterService(&_Analyzer_serviceDesc, srv)
}

func _Analyzer_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pulumirpc.Analyzer/Analyze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analyzer_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pulumirpc.Analyzer/GetPluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServer).GetPluginInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Analyzer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pulumirpc.Analyzer",
	HandlerType: (*AnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _Analyzer_Analyze_Handler,
		},
		{
			MethodName: "GetPluginInfo",
			Handler:    _Analyzer_GetPluginInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analyzer.proto",
}

func init() { proto.RegisterFile("analyzer.proto", fileDescriptor_analyzer_88854e5a6788f689) }

var fileDescriptor_analyzer_88854e5a6788f689 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0x42, 0xc9, 0x98, 0x86, 0x74, 0x25, 0xc0, 0x98, 0x1e, 0x2c, 0x9f, 0x7c, 0x72,
	0xa5, 0x70, 0xe0, 0x86, 0x30, 0x0a, 0xa5, 0x91, 0xd2, 0x04, 0x36, 0xb9, 0x70, 0x40, 0xc8, 0x75,
	0x27, 0xab, 0x95, 0xec, 0xdd, 0x65, 0x77, 0x5d, 0x29, 0x7c, 0x05, 0x37, 0x7e, 0x17, 0x65, 0xed,
	0x04, 0x8b, 0xa0, 0xde, 0x66, 0xe7, 0xbd, 0x79, 0xf3, 0x76, 0x66, 0x60, 0x94, 0x8b, 0xbc, 0xdc,
	0xfe, 0x44, 0x9d, 0x2a, 0x2d, 0xad, 0x24, 0x43, 0x55, 0x97, 0x75, 0xc5, 0xb5, 0x2a, 0xc2, 0xa7,
	0xaa, 0xac, 0x19, 0x17, 0x0d, 0x10, 0xbe, 0x66, 0x52, 0xb2, 0x12, 0x2f, 0xdd, 0xeb, 0xb6, 0xde,
	0x5c, 0x62, 0xa5, 0xec, 0xb6, 0x05, 0x2f, 0xfe, 0x05, 0x8d, 0xd5, 0x75, 0x61, 0x1b, 0x34, 0xfe,
	0x06, 0xa3, 0xac, 0xe9, 0x42, 0xf1, 0x47, 0x8d, 0xc6, 0x12, 0x02, 0x27, 0x76, 0xab, 0x30, 0xf0,
	0x22, 0x2f, 0x19, 0x52, 0x17, 0x93, 0xb7, 0x00, 0x4a, 0x4b, 0x85, 0xda, 0x72, 0x34, 0x41, 0x3f,
	0xf2, 0x12, 0x7f, 0xf2, 0x32, 0x6d, 0x84, 0xd3, 0xbd, 0x70, 0xba, 0x72, 0xc2, 0xb4, 0x43, 0x8d,
	0xbf, 0xc0, 0xb3, 0x83, 0xbc, 0x51, 0x52, 0x18, 0x24, 0xef, 0xc0, 0xbf, 0xe3, 0x39, 0x13, 0xd2,
	0x58, 0x5e, 0x98, 0xc0, 0x8b, 0x06, 0x89, 0x3f, 0xb9, 0x48, 0x0f, 0x7f, 0x4b, 0xdb, 0x82, 0xe9,
	0x81, 0x44, 0xbb, 0x05, 0xf1, 0xef, 0x3e, 0x9c, 0x1f, 0x51, 0x76, 0xae, 0x45, 0x5e, 0x1d, 0x5c,
	0xef, 0x62, 0x12, 0x81, 0x7f, 0x87, 0xa6, 0xd0, 0x5c, 0x59, 0x2e, 0x85, 0xb3, 0x3d, 0xa4, 0xdd,
	0x14, 0x09, 0xe0, 0xb4, 0x42, 0x63, 0x72, 0x86, 0xc1, 0xc0, 0xa1, 0xfb, 0xa7, 0x9b, 0x42, 0xce,
	0x4c, 0x70, 0x12, 0x0d, 0xdc, 0x14, 0x72, 0x66, 0xc8, 0x1a, 0xc6, 0x28, 0x36, 0x52, 0x17, 0x58,
	0xa1, 0xb0, 0x73, 0xbc, 0xc7, 0x32, 0x78, 0x14, 0x79, 0xc9, 0x68, 0x92, 0x3c, 0x64, 0x3f, 0x9d,
	0x4b, 0xb6, 0xc2, 0x7b, 0xd4, 0xdc, 0x6e, 0xe9, 0x91, 0x42, 0x7c, 0x0d, 0x7e, 0x87, 0x40, 0xce,
	0xe1, 0x6c, 0xb6, 0xb8, 0x5a, 0xd2, 0x9b, 0x6c, 0x3d, 0x5b, 0x2e, 0xb2, 0xf9, 0xb8, 0x47, 0x08,
	0x8c, 0x56, 0xcb, 0xab, 0xf5, 0xf7, 0x9b, 0x6c, 0x31, 0xcd, 0xd6, 0x4b, 0xfa, 0x75, 0xec, 0xed,
	0x72, 0xd7, 0x19, 0x9d, 0x76, 0x72, 0xfd, 0xc9, 0x2f, 0x0f, 0x9e, 0xb4, 0xdd, 0x35, 0xf9, 0x00,
	0xa7, 0x6d, 0x4c, 0x5e, 0x1d, 0xbb, 0x6b, 0x97, 0x1d, 0x86, 0xff, 0x83, 0x9a, 0x45, 0xc5, 0x3d,
	0xf2, 0x1e, 0xce, 0x3e, 0xa1, 0xfd, 0xec, 0x4e, 0x6d, 0x26, 0x36, 0x92, 0xbc, 0x38, 0xda, 0xf9,
	0xc7, 0xdd, 0xa5, 0x85, 0xcf, 0x3b, 0x32, 0x7f, 0xe9, 0x71, 0xef, 0xf6, 0xb1, 0x23, 0xbe, 0xf9,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x3e, 0x05, 0x61, 0xcb, 0x02, 0x00, 0x00,
}
